config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :animes do
      member do
        post 'addcollection'
      end
      member do
        patch 'switch_favorite'
        patch 'switch_finished'
      end
    end
  end
  resources :users do
    resources :mangas do
      member do
        post 'addcollection'
      end
      member do
        patch 'switch_favorite'
        patch 'switch_finished'
      end
    end
  end
  get 'animes/full_watched'
  get 'animes/full_collection'
  get 'mangas/full_read'
  get 'mangas/full_collection'
  get 'mangas/collection' => 'mangas#collection'
  get 'animes/collection' => 'animes#collection'
  root 'welcome#index'

end

app/models/manga.rb
class Manga < ActiveRecord::Base
  has_many :user_mangas
  has_many :users, through: :user_mangas
  paginates_per 7

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end

  def self.currently_reading(user)
    user_mangas_collection(user, false)
  end

  def self.finished_reading(user)
    user_mangas_collection(user, true)
  end

  private
  def self.user_mangas_collection(user, finished)
    where(id: user.user_mangas.where(finished: finished).pluck(:manga_id))
  end
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  before_action :set_manga, only: [:deletecollection]
  def index
    if params[:search]
      if current_user.mangas.count <= 0
        @mangas = Manga.search(params[:search]).order("created_at DESC")
      else
        @mangas = Manga.where('id NOT IN (?)', current_user.mangas.pluck(:id)).search(params[:search]).order("created_at DESC")
      end
        @paginatable_mangas = @mangas.page(params[:page]).per(7)
    else
      if current_user.mangas.count <= 0
        @mangas = Manga.search(params[:search]).order("created_at DESC")
      else
        @mangas = Manga.where('id NOT IN (?)', current_user.mangas.pluck(:id)).order('NAME')
      end
      @paginatable_mangas = @mangas.page(params[:page]).per(7)
    end
  end

  def full_collection
    @currently_reading = Manga.currently_reading(current_user)
  end

  def full_read
    @finished_manga_list = Manga.finished_reading(current_user)
  end

  def addcollection
    user_id = current_user.id
    if UserManga.create(user_id: user_id, manga_id: params[:id])
        redirect_to user_mangas_path, flash: {notice: 'Manga added to collection'}
    else
        redirect_to user_mangas_path, flash: {notice: 'Manga failed to be added'}
    end
  end

  def deletecollection

  end

  def switch_favorite
   if UserManga.where(manga_id: params[:id], user_id: current_user.id)[0].toggle_manga_favorite
     render json: "Success", status: 200
   else
     render json: "Failure", status: 500
   end
  end
    def switch_finished
      if UserManga.where(manga_id: params[:id], user_id: current_user.id)[0].toggle_manga_finished
        render json: "Success", status: 200
      else
        render json: "Failure", status: 500
      end
    end

  private

  def set_manga
    @manga = Manga.find(params[:id])
  end
  def manga_params
    params.require(:manga).permit(:title,:plot_summary,:image)
  end
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/views/mangas/_collection.erb
<% if @currently_reading.count >= 6 %>
  <span class="padding-button"> <%= link_to 'Read More', mangas_full_collection_path, class: 'button' %></span>
<% end %>
<% if @currently_reading == [] %>
  <h5 class="padding-button">You have no items in your collection yet, hop on over to <%= link_to 'Manga Search', user_mangas_path(current_user), class: 'color-link' %> to find some!</h5>
<% else %>
<% @currently_reading.take(6).each_slice(6).with_index do |elem, row| %>
		<div class="row">
			<% elem.each_with_index do |element, column| %>
      <div class="two columns">
				<div class="manga-box">
				  <% if element.image == 'Not Available' %>
						<div class="image-container">
						<%= image_tag "https://i.imgur.com/3vWYZyV.jpg", class: 'missing-image' %>
						</div>
						<% else %>
						<div class="image-container">
						  <%= image_tag element.image, class: 'image-collection' %>
						</div>
		      <% end %>
					<label class="btn" for="<%= "manga_collection#{row}-#{column}" %>" > <%= element.name %></label>
				</div>
	        <input class="modal-state" id="<%= "manga_collection#{row}-#{column}" %>" type="checkbox" />
	        <div class="modal">
	          <label class="modal__bg" for="<%= "manga_collection#{row}-#{column}" %>" ></label>
	          <div class="modal__inner">
	            <label class="modal__close" for="<%= "manga_collection#{row}-#{column}" %>"></label>
	            <%= element.plot_summary %>
	            <div class='toggle' id='switch'>
							<%= link_to 'Favorite', switch_favorite_user_manga_path(current_user, element) , method: :patch ,remote: true, class: 'toggle-text-off'%>
	              <div class='glow-comp'></div>
	              <div class='toggle-button'></div>
							<%= link_to 'Favorite', switch_favorite_user_manga_path(current_user, element) , method: :patch ,remote: true,class: 'toggle-text-on'%>
	            </div>
	            <div class='toggle' id='switch2'>
		            <%= link_to 'Finished Reading', switch_finished_user_manga_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-off'%>
	              <div class='glow-comp'></div>
	              <div class='toggle-button'></div>
	              <%= link_to 'Finished Reading', switch_finished_user_manga_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-on'%>
	            </div>
            </div>
          </div>
      </div>
			<% end %>
		</div>
		<% end %>
<% end %>

app/views/mangas/_read.erb
<% if @finished_manga_list.count >= 6 %>
  <span class="padding-button"> <%= link_to 'Read More',mangas_full_read_path, class: 'button' %></span>
<% end %>
<% if @finished_manga_list == [] %>
  <h5 class="padding-button">You have no items in your collection yet that have been finished, Add some when you done reading something!</h5>
<% else %>
<% @finished_manga_list.take(6).each_slice(6).with_index do |elem, row| %>
	  <div class="row">
	    <% elem.each_with_index do |element, column| %>
	      <div class="two columns">
	        <div class="anime-box">
	          <% if element.image == 'Not Available' %>
	            <div class="image-container">
	              <%= image_tag "https://i.imgur.com/3vWYZyV.jpg", class: 'missing-image' %>
	            </div>
	          <% else %>
	            <div class="image-container">
	              <%= image_tag element.image, class: 'image-collection' %>
	            </div>
	          <% end %>
	          <label class="btn" for="<%= "finished_manga_collection#{row}-#{column}" %>" > <%= element.name %></label>
	        </div>
	        <input class="modal-state" id="<%= "finished_manga_collection#{row}-#{column}" %>" type="checkbox" />
	        <div class="modal">
	          <label class="modal__bg" for="<%= "finished_manga_collection#{row}-#{column}" %>" ></label>
	          <div class="modal__inner">
	            <label class="modal__close" for="<%= "finished_manga_collection#{row}-#{column}" %>"></label>
	            <%= element.plot_summary %>
	            <div class='toggle' id='switch'>
	              <%= link_to 'Favorite', switch_favorite_user_manga_path(current_user, element) , method: :patch ,remote: true, class: 'toggle-text-off'%>
	              <div class='glow-comp'></div>
	              <div class='toggle-button'></div>
	              <%= link_to 'Favorite', switch_favorite_user_manga_path(current_user, element) , method: :patch ,remote: true,class: 'toggle-text-on'%>
	            </div>
	            <div class='toggle' id='switch2'>
	              <%= link_to 'Finished Reading', switch_finished_user_manga_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-off'%>
	              <div class='glow-comp'></div>
	              <div class='toggle-button'></div>
	              <%= link_to 'Finished Reading', switch_finished_user_manga_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-on'%>
	            </div>
	          </div>
	        </div>
	      </div>
	    <% end %>
	  </div>
	<% end %>
<% end %>

app/views/mangas/collection.erb
<div class="container">
		<% @user.mangas.each_slice(6).with_index do |elem, row| %>
		<div class="row">
			<% elem.each_with_index do |element, column| %>
      <div class="two columns">
				<div class="manga-box">
				  <% if element.image == 'Not Available' %>
						<div class="image-container">
						<%= image_tag "http://i.imgur.com/u0mao2c.png", class: 'image-collection' %>
						</div>
						<% else %>
						<div class="image-container">
						  <%= image_tag element.image, class: 'image-collection' %>
						</div>
		      <% end %>
					<label class="btn" for="<%= "#{row}-#{column}" %>" > <%= element.name %></label>
				</div>
	        <input class="modal-state" id="<%= "#{row}-#{column}" %>" type="checkbox" />
	        <div class="modal">
	          <label class="modal__bg" for="<%= "#{row}-#{column}" %>" ></label>
	          <div class="modal__inner">
	            <label class="modal__close" for="<%= "#{row}-#{column}" %>"></label>
	            <%= element.plot_summary %>
	            <div class='toggle' id='switch'>
							<%= link_to 'Favorite', switch_favorite_user_manga_path(current_user, element) , method: :patch ,remote: true, class: 'toggle-text-off'%>
	              <div class='glow-comp'></div>
	              <div class='toggle-button'></div>
							<%= link_to 'Favorite', switch_favorite_user_manga_path(current_user, element) , method: :patch ,remote: true,class: 'toggle-text-on'%>
	            </div>
	            <div class='toggle' id='switch2'>
	              <div class='toggle-text-off'>Read</div>
	              <div class='glow-comp'></div>
	              <div class='toggle-button'></div>
	              <div class='toggle-text-on'>Read</div>
	            </div>
            </div>
          </div>
      </div>
			<% end %>
		</div>
		<% end %>
</div>

app/views/mangas/full_collection.erb
<% provide(:title, "Full Currently Reading Collection") %>
<div class="container">
<% @currently_reading.each_slice(6).with_index do |elem, row| %>
  <div class="row">
    <% elem.each_with_index do |element, column| %>
      <div class="two columns">
        <div class="manga-box">
          <% if element.image == 'Not Available' %>
            <div class="image-container">
              <%= image_tag "https://i.imgur.com/3vWYZyV.jpg", class: 'missing-image' %>
            </div>
          <% else %>
            <div class="image-container">
              <%= image_tag element.image, class: 'image-collection' %>
            </div>
          <% end %>
          <label class="btn" for="<%= "manga_collection#{row}-#{column}" %>" > <%= element.name %></label>
        </div>
        <input class="modal-state" id="<%= "manga_collection#{row}-#{column}" %>" type="checkbox" />
        <div class="modal">
          <label class="modal__bg" for="<%= "manga_collection#{row}-#{column}" %>" ></label>
          <div class="modal__inner">
            <label class="modal__close" for="<%= "manga_collection#{row}-#{column}" %>"></label>
            <%= element.plot_summary %>
            <div class='toggle' id='switch'>
              <%= link_to 'Favorite', switch_favorite_user_manga_path(current_user, element) , method: :patch ,remote: true, class: 'toggle-text-off'%>
              <div class='glow-comp'></div>
              <div class='toggle-button'></div>
              <%= link_to 'Favorite', switch_favorite_user_manga_path(current_user, element) , method: :patch ,remote: true,class: 'toggle-text-on'%>
            </div>
            <div class='toggle' id='switch2'>
              <%= link_to 'Finished Reading', switch_finished_user_manga_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-off'%>
              <div class='glow-comp'></div>
              <div class='toggle-button'></div>
              <%= link_to 'Finished Reading', switch_finished_user_manga_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-on'%>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
</div>

app/views/mangas/full_read.erb
<% provide(:title, "Full Finished Reading Collection") %>
<div class="container">
<% @finished_manga_list.each_slice(6).with_index do |elem, row| %>
  <div class="row">
    <% elem.each_with_index do |element, column| %>
      <div class="two columns">
        <div class="anime-box">
          <% if element.image == 'Not Available' %>
            <div class="image-container">
              <%= image_tag "https://i.imgur.com/3vWYZyV.jpg", class: 'missing-image' %>
            </div>
          <% else %>
            <div class="image-container">
              <%= image_tag element.image, class: 'image-collection' %>
            </div>
          <% end %>
          <label class="btn" for="<%= "finished_manga_collection#{row}-#{column}" %>" > <%= element.name %></label>
        </div>
        <input class="modal-state" id="<%= "finished_manga_collection#{row}-#{column}" %>" type="checkbox" />
        <div class="modal">
          <label class="modal__bg" for="<%= "finished_manga_collection#{row}-#{column}" %>" ></label>
          <div class="modal__inner">
            <label class="modal__close" for="<%= "finished_manga_collection#{row}-#{column}" %>"></label>
            <%= element.plot_summary %>
            <div class='toggle' id='switch'>
              <%= link_to 'Favorite', switch_favorite_user_manga_path(current_user, element) , method: :patch ,remote: true, class: 'toggle-text-off'%>
              <div class='glow-comp'></div>
              <div class='toggle-button'></div>
              <%= link_to 'Favorite', switch_favorite_user_manga_path(current_user, element) , method: :patch ,remote: true,class: 'toggle-text-on'%>
            </div>
            <div class='toggle' id='switch2'>
              <%= link_to 'Finished Reading', switch_finished_user_manga_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-off'%>
              <div class='glow-comp'></div>
              <div class='toggle-button'></div>
              <%= link_to 'Finished Reading', switch_finished_user_manga_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-on'%>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
</div>

app/views/mangas/index.erb
<% provide(:title, "Manga Search") %>
<div class="container">
	<%= form_tag(user_mangas_path, :method => "get", id: "search-form") do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search For Manga" %>
	<%= submit_tag "Search" %>
	<% end %>

	<table class="u-full-width">
	  <thead>
	  <tr>
	    <th>Image</th>
	    <th>Name</th>
		  <th>Add to Collection</th>
	  </tr>
	  </thead>
	  <tbody>
	  <% @paginatable_mangas.each do |elem| %>
	  <tr class="collection-add">
		  <% if elem.image == 'Not Available' %>
			  <td><div class="image-container-search"><%= image_tag "https://i.imgur.com/3vWYZyV.jpg", class: 'image' %></div></td>
			<% else %>
	    <td><div class='image-container-search'><%= image_tag elem.image, class: 'image' %></div></td>
			<% end %>
	    <td class="name-table"><%= elem.name %></td>

	    <td><%= link_to '', addcollection_user_manga_path(current_user.id, elem.id) , class: 'fa fa-plus-square-o fa-3x fa-collection', method: :post %></td>
	  </tr>
	  <% end %>
	  </tbody>
	</table>
	<%= paginate @paginatable_mangas %>
	<%= page_entries_info @paginatable_mangas %>
</div>