config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :animes do
      member do
        post 'addcollection'
      end
      member do
        patch 'switch_favorite'
        patch 'switch_finished'
      end
    end
  end
  resources :users do
    resources :mangas do
      member do
        post 'addcollection'
      end
      member do
        patch 'switch_favorite'
        patch 'switch_finished'
      end
    end
  end
  get 'animes/full_watched'
  get 'animes/full_collection'
  get 'mangas/full_read'
  get 'mangas/full_collection'
  get 'mangas/collection' => 'mangas#collection'
  get 'animes/collection' => 'animes#collection'
  root 'welcome#index'

end

app/models/anime.rb
class Anime < ActiveRecord::Base
  has_many :user_animes
  has_many :users, through: :user_animes
  paginates_per 7
  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: [:deletecollection]
  def index
    if params[:search]
      if current_user.animes.count <= 0
        @animes = Anime.search(params[:search]).order("created_at DESC")
      else
        @animes = Anime.where('id NOT IN (?)', current_user.animes.pluck(:id)).search(params[:search]).order("created_at DESC")
      end
      @paginatable_animes = @animes.page(params[:page]).per(7)
    else
      if current_user.animes.count <= 0
        @animes = Anime.search(params[:search]).order("created_at DESC")
      else
        @animes = Anime.where('id NOT IN (?)', current_user.animes.pluck(:id)).order('NAME')
      end
      @paginatable_animes = @animes.page(params[:page]).per(7)
    end
  end

  def full_collection
    @currently_watching  = Anime.where(id: current_user.user_animes.where(finished: false).pluck(:anime_id))
  end
  def full_watched
    @finished_anime_list = Anime.where(id: current_user.user_animes.where(finished: true).pluck(:anime_id))
  end
  def addcollection
    user_id = current_user.id
    if UserAnime.create(user_id: user_id, anime_id: params[:id])
      redirect_to user_animes_path, flash: {notice: 'Anime added to collection'}
    else
      redirect_to user_animes_path, flash: {notice: 'Anime failed to be added'}
    end
  end

  def switch_favorite
    if UserAnime.where(anime_id: params[:id], user_id: current_user.id)[0].toggle_anime_favorite
      render json: "Success", status: 200
    else
      render json: "Failure", status: 500
    end
  end

  def switch_finished
    if UserAnime.where(anime_id: params[:id], user_id: current_user.id)[0].toggle_anime_finished
      render json: "Success", status: 200
    else
      render json: "Failure", status: 500
    end
  end

  def deletecollection

  end

  private

  def set_anime
    @anime = Anime.find(params[:id])
  end
  def anime_params
    params.require(:anime).permit(:title,:plot_summary,:image)
  end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/views/animes/_collection.erb
<% if @currently_watching.count >= 6 %>
  <span class="padding-button"><%= link_to 'Read More', animes_full_collection_path, class: 'button' %></span>
<% end %>
<% if @currently_watching == [] %>
	<h5 class="padding-button">You have no items in your collection yet, hop on over to <%= link_to 'Anime Search', user_animes_path(current_user), class: 'color-link' %> to find some!</h5>
	<% else %>
<% @currently_watching.take(6).each_slice(6).with_index do |elem, row| %>
    <div class="row">
      <% elem.each_with_index do |element, column| %>
        <div class="two columns">
          <div class="anime-box">
            <% if element.image == 'Not Available' %>
              <div class="image-container">
                <%= image_tag "https://i.imgur.com/3vWYZyV.jpg", class: 'missing-image' %>
              </div>
            <% else %>
              <div class="image-container">
                <%= image_tag element.image, class: 'image-collection' %>
              </div>
            <% end %>
            <label class="btn" for="<%= "anime_collection#{row}-#{column}" %>" > <%= element.name %></label>
          </div>
          <input class="modal-state" id="<%= "anime_collection#{row}-#{column}" %>" type="checkbox" />
          <div class="modal">
            <label class="modal__bg" for="<%= "anime_collection#{row}-#{column}" %>" ></label>
            <div class="modal__inner">
              <label class="modal__close" for="<%= "anime_collection#{row}-#{column}" %>"></label>
              <%= element.plot_summary %>
              <div class='toggle' id='switch'>
                <%= link_to 'Favorite', switch_favorite_user_anime_path(current_user, element) , method: :patch ,remote: true, class: 'toggle-text-off'%>
                <div class='glow-comp'></div>
                <div class='toggle-button'></div>
                <%= link_to 'Favorite', switch_favorite_user_anime_path(current_user, element) , method: :patch ,remote: true,class: 'toggle-text-on'%>
              </div>
              <div class='toggle' id='switch2'>
                <%= link_to 'Finished Watching', switch_finished_user_anime_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-off'%>
                <div class='glow-comp'></div>
                <div class='toggle-button'></div>
                <%= link_to 'Finished Watching', switch_finished_user_anime_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-on'%>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/animes/_watched.erb
<% if @finished_anime_list.count >= 6 %>
  <span class="padding-button"><%= link_to 'Read More', animes_full_watched_path, class: 'button' %></span>
<% end %>
<% if @finished_anime_list == [] %>
  <h5 class="padding-button">You have no items in your collection yet that have been finished, Add some when you done watching something!</h5>
<% else %>
<% @finished_anime_list.take(6).each_slice(6).with_index do |elem, row| %>
  <div class="row">
    <% elem.each_with_index do |element, column| %>
      <div class="two columns">
        <div class="anime-box">
          <% if element.image == 'Not Available' %>
            <div class="image-container">
              <%= image_tag "https://i.imgur.com/3vWYZyV.jpg", class: 'missing-image' %>
            </div>
          <% else %>
            <div class="image-container">
              <%= image_tag element.image, class: 'image-collection' %>
            </div>
          <% end %>
          <label class="btn" for="<%= "anime_collection#{row}-#{column}" %>" > <%= element.name %></label>
        </div>
        <input class="modal-state" id="<%= "anime_collection#{row}-#{column}" %>" type="checkbox" />
        <div class="modal">
          <label class="modal__bg" for="<%= "anime_collection#{row}-#{column}" %>" ></label>
          <div class="modal__inner">
            <label class="modal__close" for="<%= "anime_collection#{row}-#{column}" %>"></label>
            <%= element.plot_summary %>
            <div class='toggle' id='switch'>
              <%= link_to 'Favorite', switch_favorite_user_anime_path(current_user, element) , method: :patch ,remote: true, class: 'toggle-text-off'%>
              <div class='glow-comp'></div>
              <div class='toggle-button'></div>
              <%= link_to 'Favorite', switch_favorite_user_anime_path(current_user, element) , method: :patch ,remote: true,class: 'toggle-text-on'%>
            </div>
            <div class='toggle' id='switch2'>
              <%= link_to 'Finished Watching', switch_finished_user_anime_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-off'%>
              <div class='glow-comp'></div>
              <div class='toggle-button'></div>
              <%= link_to 'Finished Watching', switch_finished_user_anime_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-on'%>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<% end %>

app/views/animes/collection.erb
<div class="container">
  <% @user.animes.each_slice(6).with_index do |elem, row| %>
    <div class="row">
      <% elem.each_with_index do |element, column| %>
        <div class="two columns">
          <div class="anime-box">
            <% if element.image == 'Not Available' %>
              <div class="image-container">
                <%= image_tag "http://i.imgur.com/u0mao2c.png", class: 'image-collection' %>
              </div>
            <% else %>
              <div class="image-container">
                <%= image_tag element.image, class: 'image-collection' %>
              </div>
            <% end %>
            <label class="btn" for="<%= "#{row}-#{column}" %>" > <%= element.name %></label>
          </div>
          <input class="modal-state" id="<%= "#{row}-#{column}" %>" type="checkbox" />
          <div class="modal">
            <label class="modal__bg" for="<%= "#{row}-#{column}" %>" ></label>
            <div class="modal__inner">
              <label class="modal__close" for="<%= "#{row}-#{column}" %>"></label>
              <%= element.plot_summary %>
              <div class='toggle' id='switch'>
                <div class='toggle-text-off'>Favorite</div>
                <div class='glow-comp'></div>
                <div class='toggle-button'></div>
                <div class='toggle-text-on'>Favorite</div>
              </div>
              <div class='toggle' id='switch2'>
                <div class='toggle-text-off'>Read</div>
                <div class='glow-comp'></div>
                <div class='toggle-button'></div>
                <div class='toggle-text-on'>Read</div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/animes/full_collection.erb
<% provide(:title, "Full Currently Watching Collection") %>
<div class="container">
<% @currently_watching.each_slice(6).with_index do |elem, row| %>
  <div class="row">
    <% elem.each_with_index do |element, column| %>
      <div class="two columns">
        <div class="anime-box">
          <% if element.image == 'Not Available' %>
            <div class="image-container">
              <%= image_tag "https://i.imgur.com/3vWYZyV.jpg", class: 'missing-image' %>
            </div>
          <% else %>
            <div class="image-container">
              <%= image_tag element.image, class: 'image-collection' %>
            </div>
          <% end %>
          <label class="btn" for="<%= "anime_collection#{row}-#{column}" %>" > <%= element.name %></label>
        </div>
        <input class="modal-state" id="<%= "anime_collection#{row}-#{column}" %>" type="checkbox" />
        <div class="modal">
          <label class="modal__bg" for="<%= "anime_collection#{row}-#{column}" %>" ></label>
          <div class="modal__inner">
            <label class="modal__close" for="<%= "anime_collection#{row}-#{column}" %>"></label>
            <%= element.plot_summary %>
            <div class='toggle' id='switch'>
              <%= link_to 'Favorite', switch_favorite_user_anime_path(current_user, element) , method: :patch ,remote: true, class: 'toggle-text-off'%>
              <div class='glow-comp'></div>
              <div class='toggle-button'></div>
              <%= link_to 'Favorite', switch_favorite_user_anime_path(current_user, element) , method: :patch ,remote: true,class: 'toggle-text-on'%>
            </div>
            <div class='toggle' id='switch2'>
              <%= link_to 'Finished Watching', switch_finished_user_anime_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-off'%>
              <div class='glow-comp'></div>
              <div class='toggle-button'></div>
              <%= link_to 'Finished Watching', switch_finished_user_anime_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-on'%>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
</div>

app/views/animes/full_watched.erb
<% provide(:title, "Full Finished Watching Collection") %>
<div class="container">
<% @finished_anime_list.each_slice(6).with_index do |elem, row| %>
  <div class="row">
    <% elem.each_with_index do |element, column| %>
      <div class="two columns">
        <div class="anime-box">
          <% if element.image == 'Not Available' %>
            <div class="image-container">
              <%= image_tag "https://i.imgur.com/3vWYZyV.jpg", class: 'missing-image' %>
            </div>
          <% else %>
            <div class="image-container">
              <%= image_tag element.image, class: 'image-collection' %>
            </div>
          <% end %>
          <label class="btn" for="<%= "anime_collection#{row}-#{column}" %>" > <%= element.name %></label>
        </div>
        <input class="modal-state" id="<%= "anime_collection#{row}-#{column}" %>" type="checkbox" />
        <div class="modal">
          <label class="modal__bg" for="<%= "anime_collection#{row}-#{column}" %>" ></label>
          <div class="modal__inner">
            <label class="modal__close" for="<%= "anime_collection#{row}-#{column}" %>"></label>
            <%= element.plot_summary %>
            <div class='toggle' id='switch'>
              <%= link_to 'Favorite', switch_favorite_user_anime_path(current_user, element) , method: :patch ,remote: true, class: 'toggle-text-off'%>
              <div class='glow-comp'></div>
              <div class='toggle-button'></div>
              <%= link_to 'Favorite', switch_favorite_user_anime_path(current_user, element) , method: :patch ,remote: true,class: 'toggle-text-on'%>
            </div>
            <div class='toggle' id='switch2'>
              <%= link_to 'Finished Watching', switch_finished_user_anime_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-off'%>
              <div class='glow-comp'></div>
              <div class='toggle-button'></div>
              <%= link_to 'Finished Watching', switch_finished_user_anime_path(current_user, element), method: :patch,remote: true, class: 'toggle-text-on'%>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
</div>

app/views/animes/index.erb
<% provide(:title, "Anime Search") %>
<div class="container">
	<%= form_tag(user_animes_path, :method => "get", id: "search-form") do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search For Anime" %>
	<%= submit_tag "Search" %>
	<% end %>

	<table class="u-full-width">
	  <thead>
	  <tr>
	    <th>Image</th>
	    <th>Name</th>
		  <th>Add to Collection</th>
	  </tr>
	  </thead>
	  <tbody>
	  <% @paginatable_animes.each do |elem| %>
	  <tr class="collection-add">
		  <% if elem.image == 'Not Available' %>
			    <td><div class="image-container-search"><%= image_tag "https://i.imgur.com/3vWYZyV.jpg", class: 'image' %></div></td>
			<% else %>
	    <td><div class="image-container-search"><%= image_tag elem.image, class: 'image' %></div></td>
			<% end %>
	    <td class="name-table"><%= elem.name %></td>
	    <td><%= link_to '', addcollection_user_anime_path(current_user.id, elem.id) , class: 'fa fa-plus-square-o fa-3x fa-collection', method: :post %></td>
	  </tr>
	  <% end %>
	  </tbody>
	</table>
	<%= paginate @paginatable_animes %>
	<%= page_entries_info @paginatable_animes %>
</div>