config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :animes do
      member do
        post 'addcollection'
      end
      member do
        patch 'switch_favorite'
        patch 'switch_finished'
      end
    end
  end
  resources :users do
    resources :mangas do
      member do
        post 'addcollection'
      end
      member do
        patch 'switch_favorite'
        patch 'switch_finished'
      end
    end
  end
  get 'animes/full_watched'
  get 'animes/full_collection'
  get 'mangas/full_read'
  get 'mangas/full_collection'
  get 'mangas/collection' => 'mangas#collection'
  get 'animes/collection' => 'animes#collection'
  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Animanga | <%= yield(:title)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
</head>
<nav>
  <div class="black-line"></div>
  <div class="container">
    <div class="row">
        <div class="logo-area">
          <div class="logo">
            <h1 class="logo-animanga"><span class="animanga-logo">Animanga</span> | <span class="anime-logo">Anime</span><span class="manga-logo"> & Manga</span></h1>
          </div>
        </div>
        <div class="notice-area">
          <p class="notice" id="notice"><%= notice %></p>
          <p class="alert" id="alert"><%= alert %></p>
        </div>
      </div>
    <div id='cssmenu'>
      <ul>
        <% unless user_signed_in? %>
          <li><%= link_to 'Home', root_path, class: "home fa fa-home fa-2x fa-fw"  %></li>
          <li><%= link_to 'Sign-up' ,new_user_registration_path, class:"sign-up fa fa-plus-circle fa-2x fa-fw" %></li>
          <li><%= link_to 'Sign-in', new_user_session_path, class: "sign-in fa fa-sign-in fa-2x fa-fw" %></li>
        <% else %>
          <li><%= link_to 'Dashboard', user_path(current_user.id), class: "home fa fa-home fa-2x fa-fw"  %></li>
          <li><%= link_to 'Anime', user_animes_path(current_user.id), class: "anime fa fa-video-camera fa-2x fa-fw"  %></li>
          <li><%= link_to 'Manga', user_mangas_path(current_user.id), class: "manga fa fa-book fa-2x fa-fw"  %></li>
          <li><%= link_to 'Sign-out', destroy_user_session_path, method: :delete, class: "sign-out fa fa-sign-out fa-2x fa-fw"  %></li>
        <% end %>
      </ul>
    </div>
    <div class="main-content-divider"></div>
  </div>
</nav>

<body>
<%= yield %>
<br class="white-space">
</body>
</html>